server:
  # Use ClusterIP for internal service; Ingress will expose it externally.
  service:
    type: ClusterIP

  # Configure Ingress for Argo CD
  ingress:
    enabled: true
    ingressClassName: "nginx"
    # This hostname will be used externally
    hostname: "argocd.k8s.orb.local"
    annotations:
      # Use HTTPS when connecting to the backend
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # Force SSL redirect (recommended for secure access)
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls:
      - hosts:
          - argocd.k8s.orb.local
        secretName: argocd-tls  # Create this TLS secret or allow your cert manager to handle TLS generation
  
configs:
  cm:
    admin.enabled: "true"
    admin.account.token.enabled: "true"
    accounts.admin: apiKey