server:
  ingress:
    enabled: true
    hostname: "argocd.k8s.orb.local"  # this is the one the chart uses internally!
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    tls:
      - hosts:
          - argocd.k8s.orb.local
        secretName: argocd-tls
configs:
  cm:
    admin.enabled: "true"
    admin.account.token.enabled: "true"
    accounts.admin: apiKey