server:
  ingress:
    enabled: true
    hostname: argocd.k8s.orb.local
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    tls: 
      - hosts:
          - argocd.k8s.orb.local
        secretName: argocd-tls

configs:
  cm:
    admin.enabled: "true"
    admin.account.token.enabled: "true"
    accounts.admin: apiKey