controller:
  jenkinsUrl: "https://jenkins.k8s.orb.local/"
  # additionalPlugins:
  #   - configuration-as-code-support
  #   - EDDSA API:0.3.0-4.v84c6f0f4969e
  #   - docker-workflow

  JCasC:
    defaultConfig: false
    overwriteConfiguration: true
    configUrls:  "https://raw.githubusercontent.com/lolek1979/jenkins-config-as-code/main/jenkins.yaml"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/"
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /
    hostName: jenkins.k8s.orb.local
    tls:
      - hosts:
          - jenkins.k8s.orb.local
        secretName: jenkins-tls

  admin:
    username: admin
    password: admin

  securityRealm: "jenkins"
  authorizationStrategy: "loggedInUsersCanDoAnything"
  disableRememberMe: true
  disableSetupWizard: true

  runAsUser: 1000
  fsGroup: 1000

  persistence:
    enabled: true
    storageClass: local-path
    size: 8Gi
    # deleteClaim: false
    # annotations:
    #   "helm.sh/resource-policy": keep